### ISSUE TITLE
deletet not working when data file is autopopulated

### ISSUE THREAD

**Issue by beginner-web-developer** [AY2425S1-CS2103T-F13-4/tp#101]
`deletet` still doesnt work when the jar file is just downloaded (i.e. data file is empty) (the immutable collection problem)

**Comment by darkmoongreatsword** [comment]
I cannot recreate this bug on the current master build, it might be because we force the user to do `deletet` in transaction view. Can someone else help sanity check?

Steps I did:
1. Copy addressbook.jar to empty folder
2. java -jar addressbook.jar
3. listt 6
4. deletet 1

Deletion is successful.

**Comment by beginner-web-developer** [comment]
oh it works on the current master

**Comment by beginner-web-developer** [comment]
but why did i get a different message? My message has the wrong amount idk why
![Uploading Screenshot 2024-11-07 084225.png…]()

**Comment by beginner-web-developer** [comment]
Issue no longer present
