### ISSUE TITLE
No need to filter the person list to the current person when using `findt` and `listt`

### ISSUE THREAD

**Issue by reginateh** [AY2425S1-CS2103T-F13-4/tp#124]
`deletet` and `summary` now refer to the transaction list directly, instead of referring to the first person and their transaction list. So it might be better to remove the action that filters the person list to only one person to reduce side effects? Any thoughts? @beginner-web-developer @darkmoongreatsword

**Comment by beginner-web-developer** [comment]
wait so in this case the transaction list should not be cleared after switching to person list view? If so i need to modify PR #121

**Comment by beginner-web-developer** [comment]
also what are some side effects from filtering the person list? Are we allowing users to use all commands in both views?

**Comment by reginateh** [comment]
No, the transaction list should be cleared.

**Comment by reginateh** [comment]
It is just that we should prevent modifying the list when we don't have to?

**Comment by reginateh** [comment]
Hmm sorry I was wrong. For `deletet` we still need to know the person in order to delete the transaction for them.

**Comment by reginateh** [comment]
Please ignore this issue.
