### ISSUE TITLE
Change `findt` to be used in transaction view

### ISSUE THREAD

**Issue by reginateh** [AY2425S1-CS2103T-F13-4/tp#129]
I think that `findt` is actually more suitable to be used in transaction view. The search space will be the transactions of the person of the last `listt` command.

Advantages:
- don't need person index
- `findt` can be used sequentially without having to `list` and `findt` again
Eg. I want to find transactions of person `1` by 3 different keywords
Current: 
  1. `findt 1 keyword1`
  2. `list`
  3. `findt 1 keyword2`
  4. `list`
  5. `findt 1 keyword3`

  If `findt` is used in transaction view: 
  1. `listt 1`
  2. `findt keyword1`
  3. `findt keyword2`
  4. `findt keyword3`
 
Implementation:
1. update parser since no longer needs person index
2. change `findt` to only used in transaction view
3. when executing `findt`, update the predicate of the current transaction list
4. update error messages

Concerns:
1. take too much time to implement?
2. impact other features?

**Comment by reginateh** [comment]
@darkmoongreatsword @kngys @trpmy @beginner-web-developer any thoughts? 🙏

**Comment by trpmy** [comment]
I think it sounds reasonable. 

Currently, the only other command used in transaction view is `deletet`, which has its own kinds of errors, but because #117 collated all the errors in working environments, we can at least keep track of unintended behaviours better. I don't foresee too much side effect out of this.

Regarding implementation workload, considering we have up to next week, I'm not too anxious about that aspect (yet)

**Comment by kngys** [comment]
If `findt` is implemented to be used in the transaction view, then would it be more suitable for `addt` to be implemented for use in the transaction view as well? Would it make more sense for the user to be looking at the existing list of transactions when adding new transactions or the person list?
Let me know what are your thoughts on this thanks!

**Comment by trpmy** [comment]
I think `addt` should be in client view.

Let's say you're a fin consultant inputting some transactions, you should have already have a copy of that transaction somewhere (e.g bills, receipts, invoices) and you're just transcribing the info into the app as a notekeeper. All you need to know is looking at the client info to make sure you're putting the transaction in to the right client. It shouldn't depend on what previous transactions were.

I welcome other inputs too! This is just my personal idea. If you're convinced, can just react for bookkeeping so we don't need to change `addt` implementation.

**Comment by kngys** [comment]
In this case, I will just keep the `addt` implementation as it is? @reginateh @darkmoongreatsword @beginner-web-developer Can react if you all agree or have other opinions thanks!

**Comment by kngys** [comment]
Has this been resolved already?

**Comment by reginateh** [comment]
I am working on it
