### ISSUE TITLE
Transactions are not kept when person is edited 

### ISSUE THREAD

**Issue by kngys** [AY2425S1-CS2103T-F13-4/tp#138]
![image](https://github.com/user-attachments/assets/11a80005-dc5f-486c-a1a2-fbc86799aba1)
![image](https://github.com/user-attachments/assets/9113c54e-88d5-47c9-9d4f-a2390b1b2897)

When I used the edit command to change the tags, the transactions are not kept.

**Comment by beginner-web-developer** [comment]
I think we didnt update `EditPersonDescriptor` to store the transactions too

**Comment by kngys** [comment]
Alright I'll work on it now
