### ISSUE TITLE
Duplicates for `add` command 

### ISSUE THREAD

**Issue by kngys** [AY2425S1-CS2103T-F13-4/tp#143]
![image](https://github.com/user-attachments/assets/4dc0b8a7-7d03-494a-8a26-e56e194a5058)
![image](https://github.com/user-attachments/assets/0e4e227b-a953-4bbc-aea3-e7a463edbc49)

Currently the add command allows for adding of clients with exactly the same attributes when the name  is capitalized and not capitalized. Can consider implementing  the name checking for duplicates to be case-insensitive?

**Comment by trpmy** [comment]
Sounds reasonable! But I wonder if we can improve the duplicate handling by making it so that the name is "corrected" i.e `add john doe` adds John Doe and not john doe. Is this better?

**Comment by darkmoongreatsword** [comment]
> Sounds reasonable! But I wonder if we can improve the duplicate handling by making it so that the name is "corrected" i.e `add john doe` adds John Doe and not john doe. Is this better?

Do you want all names added to be auto-capitalised regardless of user input? So e.g every letter after whitespace and first letter in the name is capitalised

**Comment by trpmy** [comment]
> > Sounds reasonable! But I wonder if we can improve the duplicate handling by making it so that the name is "corrected" i.e `add john doe` adds John Doe and not john doe. Is this better?
> 
> Do you want all names added to be auto-capitalised regardless of user input? So e.g every letter after whitespace and first letter in the name is capitalised

Yes, that's what I'm considering. The alternative would be to put in the first instance verbatim and 1. Reject or 2. Warn later case-sensitive duplicates. Does my suggestion make sense?

**Comment by darkmoongreatsword** [comment]
> > > Sounds reasonable! But I wonder if we can improve the duplicate handling by making it so that the name is "corrected" i.e `add john doe` adds John Doe and not john doe. Is this better?
> > 
> > 
> > Do you want all names added to be auto-capitalised regardless of user input? So e.g every letter after whitespace and first letter in the name is capitalised
> 
> Yes, that's what I'm considering. The alternative would be to put in the first instance verbatim and 1. Reject or 2. Warn later case-sensitive duplicates. Does my suggestion make sense?

I think both ways make sense

**Comment by trpmy** [comment]
> > > > Sounds reasonable! But I wonder if we can improve the duplicate handling by making it so that the name is "corrected" i.e `add john doe` adds John Doe and not john doe. Is this better?
> > > 
> > > 
> > > Do you want all names added to be auto-capitalised regardless of user input? So e.g every letter after whitespace and first letter in the name is capitalised
> > 
> > 
> > Yes, that's what I'm considering. The alternative would be to put in the first instance verbatim and 1. Reject or 2. Warn later case-sensitive duplicates. Does my suggestion make sense?
> 
> I think both ways make sense

I dislike the latter because if I add john doe it keeps john doe and would be quite messy. I guess I'll just try it as I suggested and if it's too tedious I'll take the easier/safer route
