### ISSUE TITLE
Make command keywords case insensitive 

### ISSUE THREAD

**Issue by kngys** [AY2425S1-CS2103T-F13-4/tp#150]
![image](https://github.com/user-attachments/assets/8c7d12db-38b2-4385-9312-30c2d9f25706)

Right now our commands are case sensitive, which means `ADD` is considered an invalid command when `add` is valid. This is quite simple to fix, but I am wondering whether we need to make the prefixes case-insensitive as well as that may be more complicated to implement. (i.e. `add p/PHONE e/EMAIL... ` and `add P/PHONE E/EMAIL...` should both be accepted)

**Comment by kngys** [comment]
@beginner-web-developer  @reginateh @darkmoongreatsword @trpmy What are your thoughts on this?

**Comment by trpmy** [comment]
My opinion: command words insensitive, prefix sensitive

Reason: command words are forgiving because they're syntactically English anyway. Prefixes however are concrete delimiters for the info of a command. My philosophy on this is the same as why the comma is so sacred in a .csv file

Other opinions welcome!

**Comment by beginner-web-developer** [comment]
I agree that the command word should be case-insensitive.
So do we allow for "ADD", "aDd", and other variants as well? or just simply "ADD"?

**Comment by trpmy** [comment]
> I agree that the command word should be case-insensitive. So do we allow for "ADD", "aDd", and other variants as well? or just simply "ADD"?

I think we should allow variants. Sometimes typos with caps might lead to one letter capitalisation like adD or Add. Hopefully that makes sense?

**Comment by kngys** [comment]
Alright in this case I shall update to just make the command word case-insensitive
