### ISSUE TITLE
`sum` instead of `summary` command 

### ISSUE THREAD

**Issue by kngys** [AY2425S1-CS2103T-F13-4/tp#162]
![image](https://github.com/user-attachments/assets/94cabf78-aae4-4748-adc5-9f69cb0cb15a)

@reginateh I am not sure if it classifies as a feature flaw if we use `summary` as command word instead of `sum`, but just letting you know just in case. If you think it's not then feel free to close this issue!

**Comment by beginner-web-developer** [comment]
I feel that sum doesnt capture what the command does tho? Since it also filters the transactions list and not just returns the sum. @reginateh what do you think?

**Comment by reginateh** [comment]
Hmmm I think summary is ok?
