### ISSUE TITLE
[PE-D][Tester B] Handling of very large transaction inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#195]
I called this command, `addt 1 d/buy raw materials amt/9999999999999999999999999999999999999999999999999999999999999999999999999
999999999999999999999999999 o/Company ABC dt/2024-10-16` and your program, basically broke, showing the screen below. I would suggest declaring a maximum/minimum transaction amount in your user guide :)

Screenshot:

![Screenshot 2024-11-08 at 4.37.42 PM.png](https://raw.githubusercontent.com/hovanleong/ped/main/files/4a66ffaa-898b-4749-892a-3068d0c5201e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: hovanleong/ped#4

**Comment by reginateh** [comment]
This is fixed by #259 right? @beginner-web-developer

**Comment by beginner-web-developer** [comment]
yes. they cant add transactions which cause the balance to overflow

**Comment by beginner-web-developer** [comment]
but i think @kngys is adding a check for the transaction too? and in the UG

**Comment by reginateh** [comment]
Didn't you already add the check in `client.checkIsOverflow`?

**Comment by reginateh** [comment]
Ok I think this could be an issue of the parser
