### ISSUE TITLE
[PE-D][Tester A] Listing 0 transactions

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-4/tp#204]
![image.png](https://raw.githubusercontent.com/fusin02/ped/main/files/318d27ae-5ebe-41b7-b000-4ed9a2834b77.png)

Steps to reproduce: Add a new person with no transactions and listt that person

Expectation: The application should display some form of "No transaction found" rather than listing 0 transactions

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: fusin02/ped#5

**Comment by beginner-web-developer** [comment]
just a suggestion not a bug
