### ISSUE TITLE
[PE-D][Tester C] DG Bug - Typo error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#206]
![DG bug 2.png](https://raw.githubusercontent.com/jolynleow2301/ped/main/files/332dccd2-e03f-4e35-8d29-809a7e99a496.png)

There is a small typo error here, I believe it should be “JavaFX” instead of “JavaFx”.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: jolynleow2301/ped#5

**Comment by trpmy** [comment]
this is why i hate software engineers
