### ISSUE TITLE
[PE-D][Tester A] Table of Contents in UG buggy

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#222]
![image.png](https://raw.githubusercontent.com/fusin02/ped/main/files/7a34873d-cf03-4f9c-866f-0db2993a51ed.png)

The TOC seems a bit buggy here in the PDF

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: fusin02/ped#10

**Comment by trpmy** [comment]
assigning this because i think this is a markbind layout issue?

**Comment by reginateh** [comment]
Duplicate of #187

**Comment by trpmy** [comment]
See #187
