### ISSUE TITLE
[PE-D][Tester B] More screenshots in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#230]
I feel that you can consider including screenshots showing what users would on their screens for more of your features inside your UG, so that users can cross-check in split seconds that they are utilising your product correctly :)

No screenshots included as this is about the absence of something, and not something done incorrectly.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hovanleong/ped#11

**Comment by darkmoongreatsword** [comment]
I don't really agree with this one. I think we can have screenshots for some of the more complicated commands, but we shouldn't clutter the UG with screenshots for simple commands like `list`
