### ISSUE TITLE
[PE-D][Tester E] Not implicitly said what is and is not a valid date in user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#236]
![Screenshot 2024-11-08 at 5.37.57 PM.png](https://raw.githubusercontent.com/rubinnn/ped/main/files/4a36e1dd-77fc-44a6-ac49-a982ae7fd834.png)

![Screenshot 2024-11-08 at 5.37.45 PM.png](https://raw.githubusercontent.com/rubinnn/ped/main/files/1129343e-5c21-494b-8690-0581406e273b.png)

year 0000 shows an invalid date error but the documentation did not specify what is and is not a valid year, just that the format is YYYY

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: rubinnn/ped#11

**Comment by trpmy** [comment]
can anyone replicate this?

**Comment by darkmoongreatsword** [comment]
<img width="580" alt="Screenshot 2024-11-11 at 1 59 54 PM" src="https://github.com/user-attachments/assets/ecc073d0-468b-412f-b117-77b03bebd167">

**Comment by trpmy** [comment]
> PE-D build: <img alt="Screenshot 2024-11-11 at 2 00 22 PM" width="580" src="https://private-user-images.githubusercontent.com/67141937/384801230-4709a220-abaf-4eec-96c8-f1034195cac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDU0NDYsIm5iZiI6MTczMTMwNTE0NiwicGF0aCI6Ii82NzE0MTkzNy8zODQ4MDEyMzAtNDcwOWEyMjAtYWJhZi00ZWVjLTk2YzgtZjEwMzQxOTVjYWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjczNTExMGM3YTNlYjVkN2FlYzQ4MzUxMmIxY2E0ZGExOGUxMGNhMjUzMTdhNjU5MjZkOGY1NDBmMmRmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MxDCe-MOeKuXxpfBl5prFmIIJAUevDIllUNLEz-mB40">
> 
> Current master build: <img alt="Screenshot 2024-11-11 at 2 05 09 PM" width="678" src="https://private-user-images.githubusercontent.com/67141937/384802466-e1b61e36-080f-4186-ba1d-f4ecae50d47c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMDU0NDYsIm5iZiI6MTczMTMwNTE0NiwicGF0aCI6Ii82NzE0MTkzNy8zODQ4MDI0NjYtZTFiNjFlMzYtMDgwZi00MTg2LWJhMWQtZjRlY2FlNTBkNDdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDA2MDU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZjEyOTJkMTAzNmVmMTVkY2FlNmE2MzEzOTE0NmZiNmYxYTYxYTRhNDg1ZmJmZTQ2NDdkNWVmM2Q4ZDdkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JkIvG0R2-L7HtO-NE76Vf35LWeRrlKx7DsCWsfeOEIM">

Thanks! Okay then it seems everything is fine? No actions to take here
