### ISSUE TITLE
[PE-D][Tester A] Duplicate transactions allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-4/tp#237]
![image.png](https://raw.githubusercontent.com/fusin02/ped/main/files/db071c02-7e45-42c2-84b7-5da6a28eef43.png)

Steps to reproduce: Add the same transaction multiple times

Expected: Detect the duplicate and prevent the adding

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: fusin02/ped#17

**Comment by trpmy** [comment]
Suggestion: Not a flaw. It's realsitic to have multiple transactions on the same day under the same description

**Comment by kngys** [comment]
I think it's valid to allow for duplicate transactions. It is possible that one large transaction was split into smaller transactions for carrying out payment, and the user wishes to record it as such. (e.g. the scenario where a transaction amounting to `$200` is handled via payment from external company by 2 separate payments of `$100` on the same day, this would result in 2 identical transactions on same date)
