### ISSUE TITLE
[PE-D][Tester A] Edit transaction feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F13-4/tp#238]
Currently, there seems to be no way to edit my transaction other than deleting and re-adding, potentially an edit feature could be meaningfully added

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: fusin02/ped#18

**Comment by trpmy** [comment]
tagging both because it's a mix between adding and deleting. can consider spending a planned enhancement on this?

**Comment by kngys** [comment]
I think this can be included as a planned enhancement
