### ISSUE TITLE
[PE-D][Tester D] Unable to find company name containing special characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#248]
Company name allows emoji but does not match during find

![Screenshot 2024-11-08 at 20.11.48.png](https://raw.githubusercontent.com/realqijun/ped/main/files/e2114612-d17b-4b6b-a902-5dc5db53a746.png)

![Screenshot 2024-11-08 at 20.11.55.png](https://raw.githubusercontent.com/realqijun/ped/main/files/38039eb4-16ac-4229-be62-77c2b4a20947.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: realqijun/ped#8

**Comment by trpmy** [comment]
this is expected. 1 character doesnt match with 4 char string

**Comment by reginateh** [comment]
Expected behaviour. The search only matches full words. Need to separate the emojis by whitespace for them to be searched separately.
