### ISSUE TITLE
[PE-D][Tester D] Developer guide proposed implementation not explained

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#251]
![Screenshot_20241108_202526_OneDrive.jpg](https://raw.githubusercontent.com/realqijun/ped/main/files/b1186f6f-18c6-432f-b564-83c2f5434fac.jpg)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: realqijun/ped#11

**Comment by reginateh** [comment]
Maybe delete this section
