### ISSUE TITLE
[PE-D][Tester D] Sample data has Ltd and Ltd.

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F13-4/tp#254]
As program considers ltd. and ltd different words, find command cannot find their companies easily

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: realqijun/ped#14

**Comment by reginateh** [comment]
Change the search to match partial words.

**Comment by trpmy** [comment]
would that be a feature enhancement?
